export enum CountryEnum {
  AFGHANISTAN = 'AF',
  ALBANIA = 'AL',
  ALGERIA = 'DZ',
  ANDORRA = 'AD',
  ANGOLA = 'AO',
  ARGENTINA = 'AR',
  ARMENIA = 'AM',
  AUSTRALIA = 'AU',
  AUSTRIA = 'AT',
  AZERBAIJAN = 'AZ',
  BAHRAIN = 'BH',
  BANGLADESH = 'BD',
  BELARUS = 'BY',
  BELGIUM = 'BE',
  BOLIVIA = 'BO',
  BOSNIA_AND_HERZEGOVINA = 'BA',
  BRAZIL = 'BR',
  BULGARIA = 'BG',
  CAMBODIA = 'KH',
  CANADA = 'CA',
  CHILE = 'CL',
  CHINA = 'CN',
  COLOMBIA = 'CO',
  COSTA_RICA = 'CR',
  CROATIA = 'HR',
  CUBA = 'CU',
  CYPRUS = 'CY',
  CZECH_REPUBLIC = 'CZ',
  DENMARK = 'DK',
  DOMINICAN_REPUBLIC = 'DO',
  ECUADOR = 'EC',
  EGYPT = 'EG',
  EL_SALVADOR = 'SV',
  ESTONIA = 'EE',
  ETHIOPIA = 'ET',
  FINLAND = 'FI',
  FRANCE = 'FR',
  GEORGIA = 'GE',
  GERMANY = 'DE',
  GHANA = 'GH',
  GREECE = 'GR',
  GUATEMALA = 'GT',
  HONDURAS = 'HN',
  HUNGARY = 'HU',
  ICELAND = 'IS',
  INDIA = 'IN',
  INDONESIA = 'ID',
  IRAN = 'IR',
  IRAQ = 'IQ',
  IRELAND = 'IE',
  ISRAEL = 'IL',
  ITALY = 'IT',
  JAMAICA = 'JM',
  JAPAN = 'JP',
  JORDAN = 'JO',
  KAZAKHSTAN = 'KZ',
  KENYA = 'KE',
  KOSOVO = 'XK',
  KUWAIT = 'KW',
  LATVIA = 'LV',
  LEBANON = 'LB',
  LIBYA = 'LY',
  LIECHTENSTEIN = 'LI',
  LITHUANIA = 'LT',
  LUXEMBOURG = 'LU',
  MALAYSIA = 'MY',
  MALTA = 'MT',
  MEXICO = 'MX',
  MOLDOVA = 'MD',
  MONACO = 'MC',
  MONGOLIA = 'MN',
  MONTENEGRO = 'ME',
  MOROCCO = 'MA',
  MYANMAR = 'MM',
  NEPAL = 'NP',
  NETHERLANDS = 'NL',
  NEW_ZEALAND = 'NZ',
  NIGERIA = 'NG',
  NORTH_KOREA = 'KP',
  NORTH_MACEDONIA = 'MK',
  NORWAY = 'NO',
  OMAN = 'OM',
  PAKISTAN = 'PK',
  PANAMA = 'PA',
  PARAGUAY = 'PY',
  PERU = 'PE',
  PHILIPPINES = 'PH',
  POLAND = 'PL',
  PORTUGAL = 'PT',
  QATAR = 'QA',
  ROMANIA = 'RO',
  RUSSIA = 'RU',
  SAUDI_ARABIA = 'SA',
  SENEGAL = 'SN',
  SERBIA = 'RS',
  SINGAPORE = 'SG',
  SLOVAKIA = 'SK',
  SLOVENIA = 'SI',
  SOUTH_AFRICA = 'ZA',
  SOUTH_KOREA = 'KR',
  SPAIN = 'ES',
  SRI_LANKA = 'LK',
  SUDAN = 'SD',
  SWEDEN = 'SE',
  SWITZERLAND = 'CH',
  SYRIA = 'SY',
  TAIWAN = 'TW',
  TANZANIA = 'TZ',
  THAILAND = 'TH',
  TUNISIA = 'TN',
  TURKEY = 'TR',
  UGANDA = 'UG',
  UKRAINE = 'UA',
  UNITED_ARAB_EMIRATES = 'AE',
  UNITED_KINGDOM = 'UK',
  UNITED_STATES = 'US',
  URUGUAY = 'UY',
  UZBEKISTAN = 'UZ',
  VENEZUELA = 'VE',
  VIETNAM = 'VN',
  YEMEN = 'YE',
  ZAMBIA = 'ZM',
  ZIMBABWE = 'ZW',
}

export const countryNamesMap = new Map<CountryEnum, string>([
  [CountryEnum.AFGHANISTAN, 'Afghanistan'],
  [CountryEnum.ALBANIA, 'Albania'],
  [CountryEnum.ALGERIA, 'Algeria'],
  [CountryEnum.ANDORRA, 'Andorra'],
  [CountryEnum.ANGOLA, 'Angola'],
  [CountryEnum.ARGENTINA, 'Argentina'],
  [CountryEnum.ARMENIA, 'Armenia'],
  [CountryEnum.AUSTRALIA, 'Australia'],
  [CountryEnum.AUSTRIA, 'Austria'],
  [CountryEnum.AZERBAIJAN, 'Azerbaijan'],
  [CountryEnum.BAHRAIN, 'Bahrain'],
  [CountryEnum.BANGLADESH, 'Bangladesh'],
  [CountryEnum.BELARUS, 'Belarus'],
  [CountryEnum.BELGIUM, 'Belgium'],
  [CountryEnum.BOLIVIA, 'Bolivia'],
  [CountryEnum.BOSNIA_AND_HERZEGOVINA, 'Bosnia and Herzegovina'],
  [CountryEnum.BRAZIL, 'Brazil'],
  [CountryEnum.BULGARIA, 'Bulgaria'],
  [CountryEnum.CAMBODIA, 'Cambodia'],
  [CountryEnum.CANADA, 'Canada'],
  [CountryEnum.CHILE, 'Chile'],
  [CountryEnum.CHINA, 'China'],
  [CountryEnum.COLOMBIA, 'Colombia'],
  [CountryEnum.COSTA_RICA, 'Costa Rica'],
  [CountryEnum.CROATIA, 'Croatia'],
  [CountryEnum.CUBA, 'Cuba'],
  [CountryEnum.CYPRUS, 'Cyprus'],
  [CountryEnum.CZECH_REPUBLIC, 'Czech Republic'],
  [CountryEnum.DENMARK, 'Denmark'],
  [CountryEnum.DOMINICAN_REPUBLIC, 'Dominican Republic'],
  [CountryEnum.ECUADOR, 'Ecuador'],
  [CountryEnum.EGYPT, 'Egypt'],
  [CountryEnum.EL_SALVADOR, 'El Salvador'],
  [CountryEnum.ESTONIA, 'Estonia'],
  [CountryEnum.ETHIOPIA, 'Ethiopia'],
  [CountryEnum.FINLAND, 'Finland'],
  [CountryEnum.FRANCE, 'France'],
  [CountryEnum.GEORGIA, 'Georgia'],
  [CountryEnum.GERMANY, 'Germany'],
  [CountryEnum.GHANA, 'Ghana'],
  [CountryEnum.GREECE, 'Greece'],
  [CountryEnum.GUATEMALA, 'Guatemala'],
  [CountryEnum.HONDURAS, 'Honduras'],
  [CountryEnum.HUNGARY, 'Hungary'],
  [CountryEnum.ICELAND, 'Iceland'],
  [CountryEnum.INDIA, 'India'],
  [CountryEnum.INDONESIA, 'Indonesia'],
  [CountryEnum.IRAN, 'Iran'],
  [CountryEnum.IRAQ, 'Iraq'],
  [CountryEnum.IRELAND, 'Ireland'],
  [CountryEnum.ISRAEL, 'Israel'],
  [CountryEnum.ITALY, 'Italy'],
  [CountryEnum.JAMAICA, 'Jamaica'],
  [CountryEnum.JAPAN, 'Japan'],
  [CountryEnum.JORDAN, 'Jordan'],
  [CountryEnum.KAZAKHSTAN, 'Kazakhstan'],
  [CountryEnum.KENYA, 'Kenya'],
  [CountryEnum.KOSOVO, 'Kosovo'],
  [CountryEnum.KUWAIT, 'Kuwait'],
  [CountryEnum.LATVIA, 'Latvia'],
  [CountryEnum.LEBANON, 'Lebanon'],
  [CountryEnum.LIBYA, 'Libya'],
  [CountryEnum.LIECHTENSTEIN, 'Liechtenstein'],
  [CountryEnum.LITHUANIA, 'Lithuania'],
  [CountryEnum.LUXEMBOURG, 'Luxembourg'],
  [CountryEnum.MALAYSIA, 'Malaysia'],
  [CountryEnum.MALTA, 'Malta'],
  [CountryEnum.MEXICO, 'Mexico'],
  [CountryEnum.MOLDOVA, 'Moldova'],
  [CountryEnum.MONACO, 'Monaco'],
  [CountryEnum.MONGOLIA, 'Mongolia'],
  [CountryEnum.MONTENEGRO, 'Montenegro'],
  [CountryEnum.MOROCCO, 'Morocco'],
  [CountryEnum.MYANMAR, 'Myanmar'],
  [CountryEnum.NEPAL, 'Nepal'],
  [CountryEnum.NETHERLANDS, 'Netherlands'],
  [CountryEnum.NEW_ZEALAND, 'New Zealand'],
  [CountryEnum.NIGERIA, 'Nigeria'],
  [CountryEnum.NORTH_KOREA, 'North Korea'],
  [CountryEnum.NORTH_MACEDONIA, 'North Macedonia'],
  [CountryEnum.NORWAY, 'Norway'],
  [CountryEnum.OMAN, 'Oman'],
  [CountryEnum.PAKISTAN, 'Pakistan'],
  [CountryEnum.PANAMA, 'Panama'],
  [CountryEnum.PARAGUAY, 'Paraguay'],
  [CountryEnum.PERU, 'Peru'],
  [CountryEnum.PHILIPPINES, 'Philippines'],
  [CountryEnum.POLAND, 'Poland'],
  [CountryEnum.PORTUGAL, 'Portugal'],
  [CountryEnum.QATAR, 'Qatar'],
  [CountryEnum.ROMANIA, 'Romania'],
  [CountryEnum.RUSSIA, 'Russia'],
  [CountryEnum.SAUDI_ARABIA, 'Saudi Arabia'],
  [CountryEnum.SENEGAL, 'Senegal'],
  [CountryEnum.SERBIA, 'Serbia'],
  [CountryEnum.SINGAPORE, 'Singapore'],
  [CountryEnum.SLOVAKIA, 'Slovakia'],
  [CountryEnum.SLOVENIA, 'Slovenia'],
  [CountryEnum.SOUTH_AFRICA, 'South Africa'],
  [CountryEnum.SOUTH_KOREA, 'South Korea'],
  [CountryEnum.SPAIN, 'Spain'],
  [CountryEnum.SRI_LANKA, 'Sri Lanka'],
  [CountryEnum.SUDAN, 'Sudan'],
  [CountryEnum.SWEDEN, 'Sweden'],
  [CountryEnum.SWITZERLAND, 'Switzerland'],
  [CountryEnum.SYRIA, 'Syria'],
  [CountryEnum.TAIWAN, 'Taiwan'],
  [CountryEnum.TANZANIA, 'Tanzania'],
  [CountryEnum.THAILAND, 'Thailand'],
  [CountryEnum.TUNISIA, 'Tunisia'],
  [CountryEnum.TURKEY, 'Turkey'],
  [CountryEnum.UGANDA, 'Uganda'],
  [CountryEnum.UKRAINE, 'Ukraine'],
  [CountryEnum.UNITED_ARAB_EMIRATES, 'United Arab Emirates'],
  [CountryEnum.UNITED_KINGDOM, 'United Kingdom'],
  [CountryEnum.UNITED_STATES, 'United States'],
  [CountryEnum.URUGUAY, 'Uruguay'],
  [CountryEnum.UZBEKISTAN, 'Uzbekistan'],
  [CountryEnum.VENEZUELA, 'Venezuela'],
  [CountryEnum.VIETNAM, 'Vietnam'],
  [CountryEnum.YEMEN, 'Yemen'],
  [CountryEnum.ZAMBIA, 'Zambia'],
  [CountryEnum.ZIMBABWE, 'Zimbabwe'],
]);
