import {
  Client,
  Vehicle,
  Operation,
  VehicleOperation,
  User,
  InspectionPoint,
  VehicleStatus,
} from '../../core/models';

export function generateMockClients(): Client[] {
  return [
    {
      id: '1',
      name: 'John Smith',
      email: 'john@example.com',
      phone: '+44 7700 900123',
      company: 'ABC Motors',
      type: 'company',
    },
    {
      id: '2',
      name: 'Sarah Johnson',
      email: 'sarah@example.com',
      phone: '+44 7700 900456',
      company: 'XYZ Leasing',
      type: 'company',
    },
    {
      id: '3',
      name: 'Mike Williams',
      email: 'mike@example.com',
      phone: '+44 7700 900789',
      company: 'Fleet Solutions Ltd',
      type: 'company',
    },
    {
      id: '4',
      name: 'Emma Brown',
      email: 'emma@example.com',
      phone: '+44 7700 900321',
      type: 'individual',
    },
    {
      id: '5',
      name: 'James Wilson',
      email: 'james@example.com',
      phone: '+44 7700 900654',
      company: 'CarCare Services',
      type: 'company',
    },
  ];
}

export function generateMockVehicles(): Vehicle[] {
  return [
    {
      id: '1',
      licensePlate: 'AB12 CDE',
      make: 'BMW',
      model: '320d',
      year: 2022,
      registrationDate: '2022-01-01',
      engine: '2.0',
      next_entry: '2025-02-01',
      colour: 'Black',
      mileage: 45000,
      clientId: '1',
      status: 'inspection',
      jobNumber: 'JOB-2501-0001',
      createdAt: new Date('2025-01-06'),
      updatedAt: new Date(),
    },
    {
      id: '2',
      licensePlate: 'XY34 FGH',
      make: 'Audi',
      model: 'A4',
      year: 2021,
      registrationDate: '2021-05-15',
      engine: '2.0',
      next_entry: '2025-03-10',
      colour: 'White',
      mileage: 32000,
      clientId: '2',
      status: 'in_progress',
      jobNumber: 'JOB-2501-0002',
      createdAt: new Date('2025-01-07'),
      updatedAt: new Date(),
    },
    {
      id: '3',
      licensePlate: 'CD56 IJK',
      make: 'Mercedes',
      model: 'C-Class',
      year: 2023,
      registrationDate: '2023-03-20',
      engine: '1.5',
      next_entry: '2025-06-15',
      colour: 'Silver',
      mileage: 18000,
      clientId: '3',
      status: 'awaiting_approval',
      jobNumber: 'JOB-2501-0003',
      createdAt: new Date('2025-01-07'),
      updatedAt: new Date(),
    },
    {
      id: '4',
      licensePlate: 'EF78 LMN',
      make: 'Volkswagen',
      model: 'Golf',
      year: 2020,
      registrationDate: '2020-11-10',
      engine: '1.6',
      next_entry: '2024-12-01',
      colour: 'Blue',
      mileage: 67000,
      clientId: '1',
      status: 'pending',
      jobNumber: 'JOB-2501-0004',
      createdAt: new Date('2025-01-08'),
      updatedAt: new Date(),
    },
    {
      id: '5',
      licensePlate: 'GH90 OPQ',
      make: 'Ford',
      model: 'Focus',
      year: 2022,
      registrationDate: '2022-08-25',
      engine: '1.0',
      next_entry: '2025-08-25',
      colour: 'Red',
      mileage: 28000,
      clientId: '4',
      status: 'completed',
      jobNumber: 'JOB-2501-0005',
      createdAt: new Date('2025-01-05'),
      updatedAt: new Date(),
    },
    {
      id: '6',
      licensePlate: 'IJ12 RST',
      make: 'Toyota',
      model: 'Corolla',
      year: 2021,
      registrationDate: '2021-02-14',
      engine: '1.8',
      next_entry: '2025-02-14',
      colour: 'Grey',
      mileage: 42000,
      clientId: '5',
      status: 'inspection',
      jobNumber: 'JOB-2501-0006',
      createdAt: new Date('2025-01-08'),
      updatedAt: new Date(),
    },
  ];
}

export function generateMockOperations(): Operation[] {
  return [
    {
      id: '1',
      code: 'LTI',
      name: 'Light Tunnel Inspection',
      description: 'Full vehicle light inspection in tunnel',
      estimatedDuration: 30,
      defaultPrice: 45.0,
      category: 'inspection',
    },
    {
      id: '2',
      code: 'VHC',
      name: 'Vehicle Health Check',
      description: 'Complete vehicle health inspection',
      estimatedDuration: 45,
      defaultPrice: 75.0,
      category: 'inspection',
    },
    {
      id: '3',
      code: 'EXT',
      name: 'Exterior Cleaning',
      description: 'Full exterior wash and polish',
      estimatedDuration: 60,
      defaultPrice: 35.0,
      category: 'cleaning',
    },
    {
      id: '4',
      code: 'INT',
      name: 'Interior Cleaning',
      description: 'Deep interior cleaning',
      estimatedDuration: 45,
      defaultPrice: 40.0,
      category: 'cleaning',
    },
    {
      id: '5',
      code: 'TAG',
      name: 'Remove Tags/Stickers',
      description: 'Remove all dealer tags and stickers',
      estimatedDuration: 15,
      defaultPrice: 15.0,
      category: 'other',
    },
    {
      id: '6',
      code: 'TYR',
      name: 'Tyre Inspection',
      description: 'Check tyre condition and pressure',
      estimatedDuration: 20,
      defaultPrice: 20.0,
      category: 'inspection',
    },
    {
      id: '7',
      code: 'PDI',
      name: 'Pre-Delivery Inspection',
      description: 'Full pre-delivery check',
      estimatedDuration: 90,
      defaultPrice: 120.0,
      category: 'inspection',
    },
  ];
}

export function generateMockVehicleOperations(): VehicleOperation[] {
  return [
    {
      id: '1',
      vehicleId: '1',
      operationId: '1',
      status: 'completed',
      scheduledDate: new Date(),
      scheduledTime: '09:00',
      assignedUserId: '2',
    },
    {
      id: '2',
      vehicleId: '1',
      operationId: '2',
      status: 'in_progress',
      scheduledDate: new Date(),
      scheduledTime: '09:30',
      assignedUserId: '2',
    },
    {
      id: '3',
      vehicleId: '2',
      operationId: '3',
      status: 'scheduled',
      scheduledDate: new Date(),
      scheduledTime: '10:00',
      assignedUserId: '3',
    },
    { id: '4', vehicleId: '2', operationId: '4', status: 'pending' },
    {
      id: '5',
      vehicleId: '3',
      operationId: '2',
      status: 'completed',
      scheduledDate: new Date(),
      scheduledTime: '08:00',
      assignedUserId: '2',
    },
  ];
}

export function generateMockUsers(): User[] {
  return [
    {
      id: '1',
      name: 'Admin User',
      email: 'admin@arrowauto.com',
      role: 'admin',
      roles: ['admin'],
      status: 'online',
      avatar: '',
    },
    {
      id: '2',
      name: 'Dave Lee',
      email: 'dave@arrowauto.com',
      role: 'operator',
      roles: ['operator'],
      status: 'online',
      avatar: '',
    },
    {
      id: '3',
      name: 'Tom Harris',
      email: 'tom@arrowauto.com',
      role: 'operator',
      roles: ['operator'],
      status: 'online',
      avatar: '',
    },
    {
      id: '4',
      name: 'Lisa Chen',
      email: 'lisa@arrowauto.com',
      role: 'operator',
      roles: ['operator'],
      status: 'online',
      avatar: '',
    },
    {
      id: '5',
      name: 'Mark Taylor',
      email: 'mark@arrowauto.com',
      role: 'supervisor',
      roles: ['supervisor', 'operator'],
      status: 'busy',
      avatar: '',
    },
  ];
}

export function generateMockInspectionPoints(): InspectionPoint[] {
  return [
    {
      id: '1',
      code: 'FB',
      category: 'Vehicle Receiving',
      name: 'Walk around review',
      predefinedComments: ['Scratched', 'Dented', 'Cracked', 'Paint damage', 'Missing'],
    },
    {
      id: '2',
      code: 'LFE',
      category: 'Internal/Lamps/Electrics',
      name: 'Lights Front external',
      predefinedComments: ['Broken', 'Not working', 'Crack in lens'],
    },
    {
      id: '3',
      code: 'LRE',
      category: 'Internal/Lamps/Electrics',
      name: 'Lights Rear external',
      predefinedComments: ['Broken', 'Not working', 'Crack in lens'],
    },
    {
      id: '4',
      code: 'HWW',
      category: 'Internal/Lamps/Electrics',
      name: 'Horn/Wipers/Washers',
      predefinedComments: ['Not working', 'Worn blades', 'Empty washer'],
    },
    {
      id: '5',
      code: 'ACH',
      category: 'Internal/Lamps/Electrics',
      name: 'Air Con/Heating/Ventilation System',
      predefinedComments: ['Not cold', 'Noisy', 'Smell'],
    },
    {
      id: '6',
      code: 'WL',
      category: 'Internal/Lamps/Electrics',
      name: 'Warning Lamps',
      predefinedComments: ['Engine light on', 'ABS light on', 'Airbag light on'],
    },
    {
      id: '7',
      code: 'PF',
      category: 'Internal/Lamps/Electrics',
      name: 'Pollen Filter',
      predefinedComments: ['Dirty', 'Missing', 'Clogged'],
    },
    {
      id: '8',
      code: 'IC',
      category: 'Internal/Lamps/Electrics',
      name: 'Internal Condition',
      predefinedComments: ['Dirty', 'Torn seats', 'Damaged trim'],
    },
    {
      id: '9',
      code: 'EOL',
      category: 'Under Bonnet',
      name: 'Engine Oil Level/Antifreeze/Air Filter',
      predefinedComments: ['Low level', 'Dirty', 'Leak'],
    },
    {
      id: '10',
      code: 'WOF',
      category: 'Under Bonnet',
      name: 'Water/Oil/Fluid Leaks',
      predefinedComments: ['Oil leak', 'Coolant leak', 'Fuel leak'],
    },
    {
      id: '11',
      code: 'ABB',
      category: 'Under Bonnet',
      name: 'Alternator Belt/Battery',
      predefinedComments: ['Worn belt', 'Low voltage', 'Corroded terminals'],
    },
    {
      id: '12',
      code: 'BF',
      category: 'Under Bonnet',
      name: 'Brake Fluid',
      predefinedComments: ['Low level', 'Discoloured', 'Moisture content high'],
    },
    {
      id: '13',
      code: 'PSF',
      category: 'Under Bonnet',
      name: 'Power Steering Fluid',
      predefinedComments: ['Low level', 'Leak', 'Discoloured'],
    },
    {
      id: '14',
      code: 'FS',
      category: 'Under Bonnet',
      name: 'Fuel System/Fuel Filter',
      predefinedComments: ['Leak', 'Damaged lines', 'Clogged filter'],
    },
    {
      id: '15',
      code: 'SP',
      category: 'Under Bonnet',
      name: 'Spark Plugs',
      predefinedComments: ['Worn', 'Misfire', 'Due for replacement'],
    },
    {
      id: '16',
      code: 'NSFT',
      category: 'Wheels Tyres',
      name: 'N/S Front Tyre',
      predefinedComments: ['Low tread', 'Puncture', 'Side wall damage', 'Uneven wear'],
    },
    {
      id: '17',
      code: 'OSFT',
      category: 'Wheels Tyres',
      name: 'O/S Front Tyre',
      predefinedComments: ['Low tread', 'Puncture', 'Side wall damage', 'Uneven wear'],
    },
    {
      id: '18',
      code: 'OSRT',
      category: 'Wheels Tyres',
      name: 'O/S Rear Tyre',
      predefinedComments: ['Low tread', 'Puncture', 'Side wall damage', 'Uneven wear'],
    },
    {
      id: '19',
      code: 'NSRT',
      category: 'Wheels Tyres',
      name: 'N/S Rear Tyre',
      predefinedComments: ['Low tread', 'Puncture', 'Side wall damage', 'Uneven wear'],
    },
    {
      id: '20',
      code: 'W',
      category: 'Wheels Tyres',
      name: 'Wheels',
      predefinedComments: ['Kerbed', 'Buckled', 'Corroded'],
    },
    {
      id: '21',
      code: 'SS',
      category: 'Wheels Tyres',
      name: 'Space saver/Puncture Repair Kit',
      predefinedComments: ['Missing', 'Used', 'Expired sealant'],
    },
    {
      id: '22',
      code: 'WA',
      category: 'Wheels Tyres',
      name: 'Wheel Alignment',
      predefinedComments: ['Misaligned', 'Pulling to side', 'Uneven wear indication'],
    },
    {
      id: '23',
      code: 'FB',
      category: 'Brakes Hubs',
      name: 'Front Brakes',
      predefinedComments: ['Worn pads', 'Worn discs', 'Corroded'],
    },
    {
      id: '24',
      code: 'RB',
      category: 'Brakes Hubs',
      name: 'Rear Brakes',
      predefinedComments: ['Worn pads', 'Worn discs', 'Corroded', 'Shoes worn'],
    },
    {
      id: '25',
      code: 'ST',
      category: 'Underside',
      name: 'Steering',
      predefinedComments: ['Play in steering', 'Leak', 'Worn bushes'],
    },
    {
      id: '26',
      code: 'FS',
      category: 'Underside',
      name: 'Front Suspension',
      predefinedComments: ['Worn bushes', 'Leaking shock', 'Broken spring'],
    },
    {
      id: '27',
      code: 'RS',
      category: 'Underside',
      name: 'Rear Suspension',
      predefinedComments: ['Worn bushes', 'Leaking shock', 'Broken spring'],
    },
    {
      id: '28',
      code: 'VO',
      category: 'Video Overview',
      name: 'Video Overview',
      predefinedComments: [],
    },
  ];
}
